"""Vendored macro series metadata.

Point-in-time copy generated from TheEyeBetaProd:
    scripts/macro_ingestor/macro_series_registry.py

The DataAPI service is deployed independently and cannot import the macro
ingestor package at runtime, so the series metadata (name/category/frequency/
units) is vendored here. Regenerate this file when the upstream registry
changes; the upstream module remains the single source of truth.
"""

from __future__ import annotations

from app.domain.models import MacroSeriesInfo


MACRO_SERIES_METADATA: dict[str, MacroSeriesInfo] = {
    'GDPC1': MacroSeriesInfo(code='GDPC1', name='Real GDP', category='growth', frequency='quarterly', units='Billions Chained 2017 USD SAAR', seasonal_adj=True, source='FRED'),
    'GDP': MacroSeriesInfo(code='GDP', name='Nominal GDP', category='growth', frequency='quarterly', units='Billions USD SAAR', seasonal_adj=True, source='FRED'),
    'GDPDEF': MacroSeriesInfo(code='GDPDEF', name='GDP Price Deflator', category='inflation', frequency='quarterly', units='Index 2017=100 SA', seasonal_adj=True, source='FRED'),
    'INDPRO': MacroSeriesInfo(code='INDPRO', name='Industrial Production Index', category='growth', frequency='monthly', units='Index 2017=100 SA', seasonal_adj=True, source='FRED'),
    'TCU': MacroSeriesInfo(code='TCU', name='Capacity Utilization: Total Industry', category='growth', frequency='monthly', units='Percent of Capacity SA', seasonal_adj=True, source='FRED'),
    'RSAFS': MacroSeriesInfo(code='RSAFS', name='Retail Sales', category='growth', frequency='monthly', units='Millions USD SA', seasonal_adj=True, source='FRED'),
    'DGORDER': MacroSeriesInfo(code='DGORDER', name='Durable Goods Orders', category='growth', frequency='monthly', units='Millions USD SA', seasonal_adj=True, source='FRED'),
    'NEWORDER': MacroSeriesInfo(code='NEWORDER', name='Core Capex Orders (Nondefense Ex-Air)', category='growth', frequency='monthly', units='Millions USD SA', seasonal_adj=True, source='FRED'),
    'TOTALSA': MacroSeriesInfo(code='TOTALSA', name='Total Vehicle Sales', category='growth', frequency='monthly', units='Millions of Units SAAR', seasonal_adj=True, source='FRED'),
    'CFNAI': MacroSeriesInfo(code='CFNAI', name='Chicago Fed National Activity Index', category='growth', frequency='monthly', units='Standard Deviations', seasonal_adj=True, source='FRED'),
    'MANEMP': MacroSeriesInfo(code='MANEMP', name='Manufacturing Employment', category='growth', frequency='monthly', units='Thousands of Persons SA', seasonal_adj=True, source='FRED'),
    'CPIAUCSL': MacroSeriesInfo(code='CPIAUCSL', name='CPI All Items SA', category='inflation', frequency='monthly', units='Index 1982-84=100 SA', seasonal_adj=True, source='FRED'),
    'CPIAUCNS': MacroSeriesInfo(code='CPIAUCNS', name='CPI All Items NSA', category='inflation', frequency='monthly', units='Index 1982-84=100 NSA', seasonal_adj=False, source='FRED'),
    'CPILFESL': MacroSeriesInfo(code='CPILFESL', name='Core CPI (ex Food & Energy) SA', category='inflation', frequency='monthly', units='Index 1982-84=100 SA', seasonal_adj=True, source='FRED'),
    'PCEPI': MacroSeriesInfo(code='PCEPI', name='PCE Price Index', category='inflation', frequency='monthly', units='Index 2017=100 SA', seasonal_adj=True, source='FRED'),
    'PCEPILFE': MacroSeriesInfo(code='PCEPILFE', name='Core PCE Price Index', category='inflation', frequency='monthly', units='Index 2017=100 SA', seasonal_adj=True, source='FRED'),
    'PPIFIS': MacroSeriesInfo(code='PPIFIS', name='PPI Final Demand', category='inflation', frequency='monthly', units='Index Nov 2009=100 SA', seasonal_adj=True, source='FRED'),
    'CORESTICKM159SFRBATL': MacroSeriesInfo(code='CORESTICKM159SFRBATL', name='Sticky-Price CPI', category='inflation', frequency='monthly', units='Percent Change from Year Ago SA', seasonal_adj=True, source='FRED'),
    'T5YIE': MacroSeriesInfo(code='T5YIE', name='5-Year Breakeven Inflation Rate', category='inflation', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'T10YIE': MacroSeriesInfo(code='T10YIE', name='10-Year Breakeven Inflation Rate', category='inflation', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'T5YIFR': MacroSeriesInfo(code='T5YIFR', name='5-Year 5-Year Forward Inflation', category='inflation', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'CES0500000003': MacroSeriesInfo(code='CES0500000003', name='Average Hourly Earnings: All Employees', category='inflation', frequency='monthly', units='Dollars per Hour SA', seasonal_adj=True, source='FRED'),
    'ECIALLCIV': MacroSeriesInfo(code='ECIALLCIV', name='Employment Cost Index: Civilian', category='inflation', frequency='quarterly', units='Index Jun 2005=100 SA', seasonal_adj=True, source='FRED'),
    'PAYEMS': MacroSeriesInfo(code='PAYEMS', name='Nonfarm Payrolls SA', category='labor', frequency='monthly', units='Thousands of Persons SA', seasonal_adj=True, source='FRED'),
    'PAYNSA': MacroSeriesInfo(code='PAYNSA', name='Nonfarm Payrolls NSA', category='labor', frequency='monthly', units='Thousands of Persons NSA', seasonal_adj=False, source='FRED'),
    'UNRATE': MacroSeriesInfo(code='UNRATE', name='Unemployment Rate', category='labor', frequency='monthly', units='Percent SA', seasonal_adj=True, source='FRED'),
    'U6RATE': MacroSeriesInfo(code='U6RATE', name='U-6 Underemployment Rate', category='labor', frequency='monthly', units='Percent SA', seasonal_adj=True, source='FRED'),
    'ICSA': MacroSeriesInfo(code='ICSA', name='Initial Jobless Claims', category='labor', frequency='weekly', units='Number SA', seasonal_adj=True, source='FRED'),
    'CCSA': MacroSeriesInfo(code='CCSA', name='Continued Jobless Claims', category='labor', frequency='weekly', units='Number SA', seasonal_adj=True, source='FRED'),
    'JTSJOL': MacroSeriesInfo(code='JTSJOL', name='JOLTS Job Openings', category='labor', frequency='monthly', units='Thousands SA', seasonal_adj=True, source='FRED'),
    'JTSQUR': MacroSeriesInfo(code='JTSQUR', name='JOLTS Quits Rate', category='labor', frequency='monthly', units='Percent SA', seasonal_adj=True, source='FRED'),
    'CIVPART': MacroSeriesInfo(code='CIVPART', name='Labor Force Participation Rate', category='labor', frequency='monthly', units='Percent SA', seasonal_adj=True, source='FRED'),
    'EMRATIO': MacroSeriesInfo(code='EMRATIO', name='Employment-Population Ratio', category='labor', frequency='monthly', units='Percent SA', seasonal_adj=True, source='FRED'),
    'ADPMNUSNERSA': MacroSeriesInfo(code='ADPMNUSNERSA', name='ADP Total Nonfarm Private Payrolls (Monthly Level)', category='labor', frequency='monthly', units='Thousands of Persons SA', seasonal_adj=True, source='FRED'),
    'NFCI': MacroSeriesInfo(code='NFCI', name='Chicago Fed NFCI', category='credit', frequency='weekly', units='Index (0=historical avg)', seasonal_adj=False, source='FRED'),
    'ANFCI': MacroSeriesInfo(code='ANFCI', name='Adjusted Chicago Fed NFCI', category='credit', frequency='weekly', units='Index', seasonal_adj=False, source='FRED'),
    'BAMLC0A0CM': MacroSeriesInfo(code='BAMLC0A0CM', name='IG Corporate OAS', category='credit', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'BAMLH0A0HYM2': MacroSeriesInfo(code='BAMLH0A0HYM2', name='HY Corporate OAS', category='credit', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'BAMLC0A4CBBB': MacroSeriesInfo(code='BAMLC0A4CBBB', name='BBB Corporate OAS', category='credit', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'BAMLH0A0HYM2EY': MacroSeriesInfo(code='BAMLH0A0HYM2EY', name='HY Effective Yield', category='credit', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'DRTSCILM': MacroSeriesInfo(code='DRTSCILM', name='SLOOS: C&I Loan Standards Tightening', category='credit', frequency='quarterly', units='Net Percentage', seasonal_adj=False, source='FRED'),
    'DRCCLACBS': MacroSeriesInfo(code='DRCCLACBS', name='Credit Card Delinquency Rate', category='credit', frequency='quarterly', units='Percent SA', seasonal_adj=True, source='FRED'),
    'DRSFRMACBS': MacroSeriesInfo(code='DRSFRMACBS', name='Single-Family Mortgage Delinquency', category='credit', frequency='quarterly', units='Percent SA', seasonal_adj=True, source='FRED'),
    'EFFR': MacroSeriesInfo(code='EFFR', name='Fed Funds Effective Rate', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'DFEDTARU': MacroSeriesInfo(code='DFEDTARU', name='Fed Funds Target Rate Upper Bound', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'DFEDTARL': MacroSeriesInfo(code='DFEDTARL', name='Fed Funds Target Rate Lower Bound', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'SOFR': MacroSeriesInfo(code='SOFR', name='Secured Overnight Financing Rate', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'DGS1': MacroSeriesInfo(code='DGS1', name='1-Year Treasury Constant Maturity', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'DGS2': MacroSeriesInfo(code='DGS2', name='2-Year Treasury Constant Maturity', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'DGS5': MacroSeriesInfo(code='DGS5', name='5-Year Treasury Constant Maturity', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'DGS10': MacroSeriesInfo(code='DGS10', name='10-Year Treasury Constant Maturity', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'DGS30': MacroSeriesInfo(code='DGS30', name='30-Year Treasury Constant Maturity', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'DTB3': MacroSeriesInfo(code='DTB3', name='3-Month T-Bill Secondary Market Rate', category='rates', frequency='daily', units='Percent Discount Basis', seasonal_adj=False, source='FRED'),
    'T10Y2Y': MacroSeriesInfo(code='T10Y2Y', name='10Y-2Y Treasury Spread', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'T10Y3M': MacroSeriesInfo(code='T10Y3M', name='10Y-3M Treasury Spread', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'WALCL': MacroSeriesInfo(code='WALCL', name='Fed Balance Sheet Total Assets', category='rates', frequency='weekly', units='Millions USD', seasonal_adj=False, source='FRED'),
    'WRESBAL': MacroSeriesInfo(code='WRESBAL', name='Reserve Balances at Federal Reserve', category='rates', frequency='weekly', units='Millions USD', seasonal_adj=False, source='FRED'),
    'RRPONTSYD': MacroSeriesInfo(code='RRPONTSYD', name='Overnight Reverse Repo (ON RRP)', category='rates', frequency='daily', units='Billions USD', seasonal_adj=False, source='FRED'),
    'RPONTSYD': MacroSeriesInfo(code='RPONTSYD', name='Overnight Repo Operations', category='rates', frequency='daily', units='Billions USD', seasonal_adj=False, source='FRED'),
    'IORB': MacroSeriesInfo(code='IORB', name='Interest on Reserve Balances Rate', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
    'M2SL': MacroSeriesInfo(code='M2SL', name='M2 Money Supply', category='rates', frequency='monthly', units='Billions USD SA', seasonal_adj=True, source='FRED'),
    'M1SL': MacroSeriesInfo(code='M1SL', name='M1 Money Supply', category='rates', frequency='monthly', units='Billions USD SA', seasonal_adj=True, source='FRED'),
    'MORTGAGE30US': MacroSeriesInfo(code='MORTGAGE30US', name='30-Year Fixed Mortgage Rate', category='rates', frequency='weekly', units='Percent', seasonal_adj=False, source='FRED'),
    'HOUST': MacroSeriesInfo(code='HOUST', name='Housing Starts: Total', category='housing', frequency='monthly', units='Thousands of Units SAAR', seasonal_adj=True, source='FRED'),
    'PERMIT': MacroSeriesInfo(code='PERMIT', name='Building Permits: Total', category='housing', frequency='monthly', units='Thousands of Units SAAR', seasonal_adj=True, source='FRED'),
    'HSN1F': MacroSeriesInfo(code='HSN1F', name='New Single-Family Home Sales', category='housing', frequency='monthly', units='Thousands SAAR', seasonal_adj=True, source='FRED'),
    'MSPUS': MacroSeriesInfo(code='MSPUS', name='Median Sales Price: New Houses Sold', category='housing', frequency='quarterly', units='Dollars', seasonal_adj=False, source='FRED'),
    'CSUSHPINSA': MacroSeriesInfo(code='CSUSHPINSA', name='Case-Shiller National Home Price Index', category='housing', frequency='monthly', units='Index Jan 2000=100 NSA', seasonal_adj=False, source='FRED'),
    'BOPGSTB': MacroSeriesInfo(code='BOPGSTB', name='Trade Balance: Goods & Services', category='trade', frequency='monthly', units='Millions USD SA', seasonal_adj=True, source='FRED'),
    'IEABC': MacroSeriesInfo(code='IEABC', name='Current Account Balance', category='trade', frequency='quarterly', units='Millions USD SAAR', seasonal_adj=True, source='FRED'),
    'DTWEXBGS': MacroSeriesInfo(code='DTWEXBGS', name='Broad Trade-Weighted USD Index', category='trade', frequency='daily', units='Index (Mar 1973=100)', seasonal_adj=False, source='FRED'),
    'DEXUSEU': MacroSeriesInfo(code='DEXUSEU', name='EUR/USD Exchange Rate', category='trade', frequency='daily', units='USD per EUR', seasonal_adj=False, source='FRED'),
    'DEXJPUS': MacroSeriesInfo(code='DEXJPUS', name='USD/JPY Exchange Rate', category='trade', frequency='daily', units='JPY per USD', seasonal_adj=False, source='FRED'),
    'DEXCHUS': MacroSeriesInfo(code='DEXCHUS', name='USD/CNY Exchange Rate', category='trade', frequency='daily', units='CNY per USD', seasonal_adj=False, source='FRED'),
    'DEXUSUK': MacroSeriesInfo(code='DEXUSUK', name='GBP/USD Exchange Rate', category='trade', frequency='daily', units='USD per GBP', seasonal_adj=False, source='FRED'),
    'UMCSENT': MacroSeriesInfo(code='UMCSENT', name='UMich Consumer Sentiment Index', category='sentiment', frequency='monthly', units='Index (1966Q1=100)', seasonal_adj=False, source='FRED'),
    'PI': MacroSeriesInfo(code='PI', name='Personal Income', category='sentiment', frequency='monthly', units='Billions USD SAAR', seasonal_adj=True, source='FRED'),
    'PCE': MacroSeriesInfo(code='PCE', name='Personal Consumption Expenditures', category='sentiment', frequency='monthly', units='Billions USD SAAR', seasonal_adj=True, source='FRED'),
    'PSAVERT': MacroSeriesInfo(code='PSAVERT', name='Personal Saving Rate', category='sentiment', frequency='monthly', units='Percent SA', seasonal_adj=True, source='FRED'),
    'REVOLSL': MacroSeriesInfo(code='REVOLSL', name='Revolving Consumer Credit Outstanding', category='sentiment', frequency='monthly', units='Billions USD SA', seasonal_adj=True, source='FRED'),
    'CCLACBW027SBOG': MacroSeriesInfo(code='CCLACBW027SBOG', name='Credit Card Loans: All Commercial Banks', category='sentiment', frequency='weekly', units='Millions USD SA', seasonal_adj=True, source='FRED'),
    'RECPROUSM156N': MacroSeriesInfo(code='RECPROUSM156N', name='Smoothed US Recession Probabilities', category='leading', frequency='monthly', units='Probability (0-1)', seasonal_adj=False, source='FRED'),
    'DCOILWTICO': MacroSeriesInfo(code='DCOILWTICO', name='WTI Crude Oil Spot Price', category='commodities', frequency='daily', units='Dollars per Barrel', seasonal_adj=False, source='FRED'),
    'DCOILBRENTEU': MacroSeriesInfo(code='DCOILBRENTEU', name='Brent Crude Oil Spot Price', category='commodities', frequency='daily', units='Dollars per Barrel', seasonal_adj=False, source='FRED'),
    'DHHNGSP': MacroSeriesInfo(code='DHHNGSP', name='Henry Hub Natural Gas Spot Price', category='commodities', frequency='daily', units='Dollars per MMBTU', seasonal_adj=False, source='FRED'),
    'PNRGINDEXM': MacroSeriesInfo(code='PNRGINDEXM', name='Global Price of Energy Index', category='commodities', frequency='monthly', units='Index 2016=100', seasonal_adj=False, source='FRED'),
    'PALLFNFINDEXM': MacroSeriesInfo(code='PALLFNFINDEXM', name='Global Price of All Commodities', category='commodities', frequency='monthly', units='Index 2016=100', seasonal_adj=False, source='FRED'),
    'PCOPPUSDM': MacroSeriesInfo(code='PCOPPUSDM', name='Global Price of Copper', category='commodities', frequency='monthly', units='USD per Metric Ton', seasonal_adj=False, source='FRED'),
    'VIXCLS': MacroSeriesInfo(code='VIXCLS', name='VIX Volatility Index', category='risk', frequency='daily', units='Index', seasonal_adj=False, source='FRED'),
    'SP500': MacroSeriesInfo(code='SP500', name='S&P 500 Index', category='risk', frequency='daily', units='Index', seasonal_adj=False, source='FRED'),
    'MTSDS133FMS': MacroSeriesInfo(code='MTSDS133FMS', name='Federal Surplus/Deficit (MTS)', category='fiscal', frequency='monthly', units='Millions USD NSA', seasonal_adj=False, source='FRED'),
    'GFDEBTN': MacroSeriesInfo(code='GFDEBTN', name='Federal Debt: Total', category='fiscal', frequency='quarterly', units='Millions USD', seasonal_adj=False, source='FRED'),
    'GFDEGDQ188S': MacroSeriesInfo(code='GFDEGDQ188S', name='Federal Debt as % of GDP', category='fiscal', frequency='quarterly', units='Percent of GDP SA', seasonal_adj=True, source='FRED'),
    'WTREGEN': MacroSeriesInfo(code='WTREGEN', name='Treasury General Account (TGA)', category='fiscal', frequency='weekly', units='Millions USD', seasonal_adj=False, source='FRED'),
    'CP0000EZ19M086NEST': MacroSeriesInfo(code='CP0000EZ19M086NEST', name='Euro Area CPI YoY', category='global', frequency='monthly', units='Percent Change from Year Ago', seasonal_adj=False, source='FRED'),
    'CPALTT01JPM659N': MacroSeriesInfo(code='CPALTT01JPM659N', name='Japan CPI YoY', category='global', frequency='monthly', units='Percent Change from Year Ago', seasonal_adj=False, source='FRED'),
    'CPALTT01GBM659N': MacroSeriesInfo(code='CPALTT01GBM659N', name='UK CPI YoY', category='global', frequency='monthly', units='Percent Change from Year Ago', seasonal_adj=False, source='FRED'),
    'G7LOLITOAASTSAM': MacroSeriesInfo(code='G7LOLITOAASTSAM', name='OECD Leading Indicator: G7', category='global', frequency='monthly', units='Index', seasonal_adj=True, source='FRED'),
    'GEPUPPP': MacroSeriesInfo(code='GEPUPPP', name='Global Econ Policy Uncertainty Index', category='global', frequency='monthly', units='Index', seasonal_adj=False, source='FRED'),
    'ISM_MFG_PMI': MacroSeriesInfo(code='ISM_MFG_PMI', name='ISM Manufacturing PMI', category='growth', frequency='monthly', units='Index (>50=expansion)', seasonal_adj=True, source='ISM'),
    'ISM_MFG_NEW_ORDERS': MacroSeriesInfo(code='ISM_MFG_NEW_ORDERS', name='ISM Manufacturing New Orders Index', category='growth', frequency='monthly', units='Index (>50=expansion)', seasonal_adj=True, source='ISM'),
    'ISM_MFG_EMPLOYMENT': MacroSeriesInfo(code='ISM_MFG_EMPLOYMENT', name='ISM Manufacturing Employment Index', category='labor', frequency='monthly', units='Index (>50=expansion)', seasonal_adj=True, source='ISM'),
    'ISM_SVCS_PMI': MacroSeriesInfo(code='ISM_SVCS_PMI', name='ISM Services PMI', category='growth', frequency='monthly', units='Index (>50=expansion)', seasonal_adj=True, source='ISM'),
    'CB_LEI': MacroSeriesInfo(code='CB_LEI', name='Conference Board Leading Economic Index', category='leading', frequency='monthly', units='Index 2016=100', seasonal_adj=True, source='Conference Board'),
    'CB_CONSUMER_CONF': MacroSeriesInfo(code='CB_CONSUMER_CONF', name='Conference Board Consumer Confidence Index', category='sentiment', frequency='monthly', units='Index 1985=100', seasonal_adj=True, source='Conference Board'),
    'NAHB_HMI': MacroSeriesInfo(code='NAHB_HMI', name='NAHB Housing Market Index', category='housing', frequency='monthly', units='Index (>50=positive)', seasonal_adj=True, source='NAHB / Wells Fargo'),
    'MOVE_INDEX': MacroSeriesInfo(code='MOVE_INDEX', name='MOVE Index (Treasury Volatility)', category='risk', frequency='daily', units='Index', seasonal_adj=False, source='ICE BofA'),
    'US_PMI_COMPOSITE': MacroSeriesInfo(code='US_PMI_COMPOSITE', name='S&P Global US PMI Composite', category='growth', frequency='monthly', units='Index (>50=expansion)', seasonal_adj=True, source='S&P Global'),
}

MACRO_SERIES_METADATA.update(
    {
        'BREAKEVEN_10Y': MacroSeriesInfo(code='BREAKEVEN_10Y', name='10-Year Breakeven Inflation Rate (Alias)', category='inflation', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
        'BREAKEVEN_5Y': MacroSeriesInfo(code='BREAKEVEN_5Y', name='5-Year Breakeven Inflation Rate (Alias)', category='inflation', frequency='daily', units='Percent', seasonal_adj=False, source='FRED'),
        'GOLDPMGBD228NLBM': MacroSeriesInfo(code='GOLDPMGBD228NLBM', name='Gold Price (COMEX GC=F)', category='commodities', frequency='daily', units='USD per Troy Ounce', seasonal_adj=False, source='yfinance/COMEX'),
        'IG_OAS': MacroSeriesInfo(code='IG_OAS', name='Investment Grade Corporate OAS', category='credit', frequency='daily', units='Basis points', seasonal_adj=False, source='FRED'),
        'NONFARM_PAYROLLS': MacroSeriesInfo(code='NONFARM_PAYROLLS', name='Nonfarm Payrolls Monthly Change', category='labor', frequency='monthly', units='Thousands of Persons MoM', seasonal_adj=True, source='FRED derived'),
        'NONFARM_PAYROLLS_LEVEL': MacroSeriesInfo(code='NONFARM_PAYROLLS_LEVEL', name='Nonfarm Payrolls Level', category='labor', frequency='monthly', units='Thousands of Persons SA', seasonal_adj=True, source='FRED'),
        'PCE_CORE': MacroSeriesInfo(code='PCE_CORE', name='Core PCE YoY', category='inflation', frequency='monthly', units='Percent Change from Year Ago', seasonal_adj=True, source='FRED derived'),
        'PCE_CORE_INDEX': MacroSeriesInfo(code='PCE_CORE_INDEX', name='Core PCE Price Index', category='inflation', frequency='monthly', units='Index 2017=100 SA', seasonal_adj=True, source='FRED'),
        'UNEMPLOYMENT_RATE': MacroSeriesInfo(code='UNEMPLOYMENT_RATE', name='Unemployment Rate (Alias)', category='labor', frequency='monthly', units='Percent SA', seasonal_adj=True, source='FRED'),
        'cpi': MacroSeriesInfo(code='cpi', name='CPI All Items SA (Regime Input)', category='inflation', frequency='daily', units='Index 1982-84=100 SA', seasonal_adj=True, source='fred+yfinance'),
        'dxy': MacroSeriesInfo(code='dxy', name='US Dollar Index (Regime Input)', category='trade', frequency='daily', units='Index', seasonal_adj=False, source='fred+yfinance'),
        'fed_funds_rate': MacroSeriesInfo(code='fed_funds_rate', name='Fed Funds Rate (Regime Input)', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='fred+yfinance'),
        'gdp': MacroSeriesInfo(code='gdp', name='Real GDP (Regime Input)', category='growth', frequency='daily', units='Billions Chained 2017 USD SAAR', seasonal_adj=True, source='fred+yfinance'),
        'hy_oas_bps': MacroSeriesInfo(code='hy_oas_bps', name='HY Corporate OAS (Regime Input)', category='credit', frequency='daily', units='Basis points', seasonal_adj=False, source='fred+yfinance'),
        'nasdaq_change_pct': MacroSeriesInfo(code='nasdaq_change_pct', name='Nasdaq Change Percent (Regime Input)', category='risk', frequency='daily', units='Percent', seasonal_adj=False, source='fred+yfinance'),
        'nasdaq_level': MacroSeriesInfo(code='nasdaq_level', name='Nasdaq Composite Level (Regime Input)', category='risk', frequency='daily', units='Index', seasonal_adj=False, source='fred+yfinance'),
        'sp500_change_pct': MacroSeriesInfo(code='sp500_change_pct', name='S&P 500 Change Percent (Regime Input)', category='risk', frequency='daily', units='Percent', seasonal_adj=False, source='fred+yfinance'),
        'sp500_level': MacroSeriesInfo(code='sp500_level', name='S&P 500 Level (Regime Input)', category='risk', frequency='daily', units='Index', seasonal_adj=False, source='fred+yfinance'),
        'spread_2s10s': MacroSeriesInfo(code='spread_2s10s', name='10Y-2Y Treasury Spread (Regime Input)', category='rates', frequency='daily', units='Percentage points', seasonal_adj=False, source='fred+yfinance'),
        'vix': MacroSeriesInfo(code='vix', name='VIX Volatility Index (Regime Input)', category='risk', frequency='daily', units='Index', seasonal_adj=False, source='fred+yfinance'),
        'yield_10y': MacroSeriesInfo(code='yield_10y', name='10-Year Treasury Yield (Regime Input)', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='fred+yfinance'),
        'yield_2y': MacroSeriesInfo(code='yield_2y', name='2-Year Treasury Yield (Regime Input)', category='rates', frequency='daily', units='Percent', seasonal_adj=False, source='fred+yfinance'),
    }
)

MACRO_CATEGORIES: list[str] = sorted({m.category for m in MACRO_SERIES_METADATA.values()})
