-- GENERATED by scripts/prod_contract_snapshot.sh from TheEyeBetaProd @ 47d042f8c8b36308b07a88ad4d00050015772739.
-- Role and grants that Prod migrations create for the DataAPI policy reader.
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'api_readonly') THEN CREATE ROLE api_readonly NOLOGIN; END IF; END $$;
GRANT SELECT ON TABLE theeyebeta.dataapi_applications TO api_readonly;
GRANT SELECT ON TABLE theeyebeta.dataapi_credential_revocations TO api_readonly;
GRANT SELECT ON TABLE theeyebeta.dataapi_entitlements TO api_readonly;
GRANT SELECT ON TABLE theeyebeta.dataapi_locks TO api_readonly;
GRANT SELECT ON TABLE theeyebeta.dataapi_memberships TO api_readonly;
GRANT SELECT ON TABLE theeyebeta.dataapi_policy_versions TO api_readonly;
GRANT SELECT ON TABLE theeyebeta.dataapi_quota_windows TO api_readonly;
GRANT SELECT ON TABLE theeyebeta.dataapi_tenants TO api_readonly;
GRANT USAGE ON SCHEMA theeyebeta TO api_readonly;
