-- GENERATED by scripts/prod_contract_snapshot.sh. Do not edit by hand.
-- Source: TheEyeBetaProd @ 47d042f8c8b36308b07a88ad4d00050015772739 (alembic head 0102_news_dedupe_uniq)
-- Objects: contracts/prod/objects.txt (theeyebeta objects TheEyeBetaDataAPI reads)
CREATE SCHEMA IF NOT EXISTS theeyebeta;
CREATE TABLE theeyebeta.audit_cap_events (
    id bigint NOT NULL,
    trade_date date NOT NULL,
    symbol text NOT NULL,
    instrument_id bigint,
    event_type text NOT NULL,
    market_cap numeric(20,2) NOT NULL,
    prior_market_cap numeric(20,2),
    action_required text NOT NULL,
    universe_updated boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_false_positive boolean DEFAULT false NOT NULL,
    corrected_at timestamp with time zone,
    correction_note text,
    CONSTRAINT audit_cap_events_event_type_check CHECK ((event_type = ANY (ARRAY['CROSSED_UP'::text, 'CROSSED_DOWN'::text])))
);

CREATE SEQUENCE theeyebeta.audit_cap_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.audit_cap_events_id_seq OWNED BY theeyebeta.audit_cap_events.id;

CREATE TABLE theeyebeta.audit_log (
    id bigint NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    actor text NOT NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    payload jsonb NOT NULL,
    prev_hash bytea,
    row_hash bytea NOT NULL
)
PARTITION BY RANGE (ts);

CREATE SEQUENCE theeyebeta.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.audit_log_id_seq OWNED BY theeyebeta.audit_log.id;

CREATE TABLE theeyebeta.audit_log_2026_10 (
    id bigint DEFAULT nextval('theeyebeta.audit_log_id_seq'::regclass) NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    actor text NOT NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    payload jsonb NOT NULL,
    prev_hash bytea,
    row_hash bytea NOT NULL
);

CREATE TABLE theeyebeta.audit_log_2026_11 (
    id bigint DEFAULT nextval('theeyebeta.audit_log_id_seq'::regclass) NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    actor text NOT NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    payload jsonb NOT NULL,
    prev_hash bytea,
    row_hash bytea NOT NULL
);

CREATE TABLE theeyebeta.audit_log_2026_12 (
    id bigint DEFAULT nextval('theeyebeta.audit_log_id_seq'::regclass) NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    actor text NOT NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    payload jsonb NOT NULL,
    prev_hash bytea,
    row_hash bytea NOT NULL
);

CREATE TABLE theeyebeta.audit_log_2027_01 (
    id bigint DEFAULT nextval('theeyebeta.audit_log_id_seq'::regclass) NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    actor text NOT NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    payload jsonb NOT NULL,
    prev_hash bytea,
    row_hash bytea NOT NULL
);

CREATE TABLE theeyebeta.audit_log_2027_02 (
    id bigint DEFAULT nextval('theeyebeta.audit_log_id_seq'::regclass) NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    actor text NOT NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    payload jsonb NOT NULL,
    prev_hash bytea,
    row_hash bytea NOT NULL
);

CREATE TABLE theeyebeta.audit_log_2027_03 (
    id bigint DEFAULT nextval('theeyebeta.audit_log_id_seq'::regclass) NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    actor text NOT NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    payload jsonb NOT NULL,
    prev_hash bytea,
    row_hash bytea NOT NULL
);

CREATE TABLE theeyebeta.audit_log_2027_04 (
    id bigint DEFAULT nextval('theeyebeta.audit_log_id_seq'::regclass) NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    actor text NOT NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    payload jsonb NOT NULL,
    prev_hash bytea,
    row_hash bytea NOT NULL
);

CREATE TABLE theeyebeta.corporate_actions (
    id bigint NOT NULL,
    instrument_id bigint NOT NULL,
    ex_date date NOT NULL,
    action_type text NOT NULL,
    ratio_num numeric(18,8),
    ratio_den numeric(18,8),
    cash_amount numeric(18,6),
    currency_iso character(3),
    metadata jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT corporate_actions_action_type_check CHECK ((action_type = ANY (ARRAY['split'::text, 'dividend'::text, 'merger'::text, 'spinoff'::text, 'rename'::text])))
);

CREATE SEQUENCE theeyebeta.corporate_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.corporate_actions_id_seq OWNED BY theeyebeta.corporate_actions.id;

CREATE TABLE theeyebeta.dataapi_applications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    client_id text NOT NULL,
    product text NOT NULL,
    status text DEFAULT 'ACTIVE'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_dataapi_applications_product CHECK ((product = ANY (ARRAY['INTERNAL'::text, 'LENS'::text]))),
    CONSTRAINT ck_dataapi_applications_status CHECK ((status = ANY (ARRAY['ACTIVE'::text, 'SUSPENDED'::text, 'DISABLED'::text])))
);

CREATE TABLE theeyebeta.dataapi_credential_revocations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    token_id text NOT NULL,
    reason text NOT NULL,
    revoked_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE theeyebeta.dataapi_entitlements (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    policy_version_id uuid NOT NULL,
    code text NOT NULL,
    status text DEFAULT 'ACTIVE'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_dataapi_entitlements_status CHECK ((status = ANY (ARRAY['ACTIVE'::text, 'SUSPENDED'::text, 'REVOKED'::text])))
);

CREATE TABLE theeyebeta.dataapi_locks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    scope_type text NOT NULL,
    scope_id text NOT NULL,
    reason text NOT NULL,
    idempotency_key text NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    CONSTRAINT ck_dataapi_locks_scope_type CHECK ((scope_type = ANY (ARRAY['GLOBAL'::text, 'TENANT'::text, 'APPLICATION'::text, 'SUBJECT'::text, 'CREDENTIAL'::text, 'DATASET'::text])))
);

CREATE TABLE theeyebeta.dataapi_memberships (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    external_subject text NOT NULL,
    status text DEFAULT 'ACTIVE'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_dataapi_memberships_status CHECK ((status = ANY (ARRAY['ACTIVE'::text, 'SUSPENDED'::text, 'DISABLED'::text])))
);

CREATE TABLE theeyebeta.dataapi_policy_versions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    version integer NOT NULL,
    status text DEFAULT 'DRAFT'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    effective_from timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_dataapi_policy_versions_status CHECK ((status = ANY (ARRAY['DRAFT'::text, 'ACTIVE'::text, 'RETIRED'::text])))
);

CREATE TABLE theeyebeta.dataapi_quota_windows (
    tenant_id uuid NOT NULL,
    subject text NOT NULL,
    window_started_at timestamp with time zone NOT NULL,
    request_count integer DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_dataapi_quota_windows_request_count CHECK ((request_count >= 0))
);

CREATE TABLE theeyebeta.dataapi_tenants (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    slug text NOT NULL,
    display_name text NOT NULL,
    status text DEFAULT 'ACTIVE'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_dataapi_tenants_status CHECK ((status = ANY (ARRAY['ACTIVE'::text, 'SUSPENDED'::text, 'DISABLED'::text])))
);

CREATE TABLE theeyebeta.exchanges (
    id smallint NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    country_iso2 character(2) NOT NULL,
    timezone text NOT NULL,
    currency_iso character(3) NOT NULL
);

CREATE SEQUENCE theeyebeta.exchanges_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.exchanges_id_seq OWNED BY theeyebeta.exchanges.id;

CREATE TABLE theeyebeta.fixed_income_curve_metrics (
    date date NOT NULL,
    country text DEFAULT 'US'::text NOT NULL,
    currency text DEFAULT 'USD'::text NOT NULL,
    y_1mo numeric(10,4),
    y_3mo numeric(10,4),
    y_6mo numeric(10,4),
    y_1y numeric(10,4),
    y_2y numeric(10,4),
    y_5y numeric(10,4),
    y_10y numeric(10,4),
    y_20y numeric(10,4),
    y_30y numeric(10,4),
    spread_10y_2y numeric(10,4),
    spread_10y_3m numeric(10,4),
    spread_30y_5y numeric(10,4),
    real_yield_10y numeric(10,4),
    high_yield_spread numeric(10,4),
    ig_corp_spread numeric(10,4),
    y_2y_change_5d numeric(10,4),
    y_10y_change_5d numeric(10,4),
    y_30y_change_5d numeric(10,4),
    y_2y_change_20d numeric(10,4),
    y_10y_change_20d numeric(10,4),
    y_30y_change_20d numeric(10,4),
    y_10y_volatility_20d numeric(10,4),
    curve_regime text DEFAULT 'unknown'::text NOT NULL,
    rate_regime text DEFAULT 'unknown'::text NOT NULL,
    credit_regime text DEFAULT 'unknown'::text NOT NULL,
    bond_environment_score integer,
    bond_environment_label text,
    source text DEFAULT 'fred'::text NOT NULL,
    computed_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT fixed_income_curve_metrics_bond_environment_score_check CHECK (((bond_environment_score IS NULL) OR ((bond_environment_score >= 0) AND (bond_environment_score <= 100))))
);

CREATE TABLE theeyebeta.fixed_income_signals (
    id bigint NOT NULL,
    date date NOT NULL,
    country text DEFAULT 'US'::text NOT NULL,
    signal_name text NOT NULL,
    signal_value numeric(12,4),
    signal_strength text NOT NULL,
    signal_direction text NOT NULL,
    interpretation text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE theeyebeta.fixed_income_signals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.fixed_income_signals_id_seq OWNED BY theeyebeta.fixed_income_signals.id;

CREATE TABLE theeyebeta.fundamentals (
    id bigint NOT NULL,
    instrument_id bigint NOT NULL,
    period_end date NOT NULL,
    period_type text NOT NULL,
    revenue numeric(20,2),
    net_income numeric(20,2),
    eps numeric(12,4),
    pe_ratio numeric(12,4),
    pb_ratio numeric(12,4),
    debt_to_equity numeric(12,4),
    roe numeric(12,6),
    gross_margin numeric(12,6),
    free_cash_flow numeric(20,2),
    raw jsonb DEFAULT '{}'::jsonb NOT NULL,
    source text NOT NULL,
    ingested_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT fundamentals_period_type_check CHECK ((period_type = ANY (ARRAY['Q'::text, 'A'::text, 'TTM'::text])))
);

CREATE TABLE theeyebeta.fundamentals_company (
    ticker_id bigint NOT NULL,
    sector character varying(100),
    industry character varying(100),
    sub_industry character varying(100),
    ceo character varying(200),
    full_time_employees integer,
    headquarters_city character varying(100),
    headquarters_state character varying(50),
    headquarters_country character varying(100),
    market_cap numeric,
    enterprise_value numeric,
    shares_outstanding numeric,
    float_shares numeric,
    pe_ratio numeric,
    pe_forward numeric,
    peg_ratio numeric,
    price_to_book numeric,
    price_to_sales numeric,
    ev_to_ebitda numeric,
    ev_to_revenue numeric,
    dividend_rate numeric,
    dividend_yield numeric,
    ex_dividend_date date,
    payout_ratio numeric,
    currency character varying(3) DEFAULT 'USD'::character varying,
    source character varying(50),
    last_updated timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    instrument_id bigint
);

CREATE SEQUENCE theeyebeta.fundamentals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.fundamentals_id_seq OWNED BY theeyebeta.fundamentals.id;

CREATE TABLE theeyebeta.ind_technical_daily (
    instrument_id bigint NOT NULL,
    date date NOT NULL,
    ticker_id bigint NOT NULL,
    sma_10 numeric(20,6),
    sma_50 numeric(20,6),
    sma_200 numeric(20,6),
    ema_10 numeric(20,6),
    ema_50 numeric(20,6),
    ema_200 numeric(20,6),
    rsi_14 numeric(12,4),
    macd numeric(20,6),
    macd_signal numeric(20,6),
    macd_hist numeric(20,6),
    roc_10 numeric(12,4),
    roc_20 numeric(12,4),
    golden_cross_sma boolean,
    death_cross_sma boolean,
    as_of_date date,
    computed_at timestamp with time zone,
    price_field text,
    compute_version text,
    ema_12 numeric(20,6),
    ema_26 numeric(20,6),
    momentum_rank_12_1 numeric(12,4)
);

CREATE TABLE theeyebeta.instruments (
    id bigint NOT NULL,
    symbol text NOT NULL,
    exchange_id smallint NOT NULL,
    isin text,
    cusip text,
    figi text,
    asset_class text NOT NULL,
    sector text,
    industry text,
    active boolean DEFAULT true NOT NULL,
    listed_at date,
    delisted_at date,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT instruments_asset_class_check CHECK ((asset_class = ANY (ARRAY['equity'::text, 'etf'::text, 'adr'::text, 'index'::text, 'crypto'::text])))
);

CREATE SEQUENCE theeyebeta.instruments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.instruments_id_seq OWNED BY theeyebeta.instruments.id;

CREATE TABLE theeyebeta.market_cap_daily (
    id bigint NOT NULL,
    symbol text NOT NULL,
    instrument_id bigint,
    as_of_date date NOT NULL,
    market_cap numeric(20,2) NOT NULL,
    close_price numeric(20,6),
    shares_outstanding bigint,
    source text DEFAULT 'massive'::text NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE theeyebeta.prices_daily (
    instrument_id bigint NOT NULL,
    ts timestamp with time zone NOT NULL,
    open numeric(18,6) NOT NULL,
    high numeric(18,6) NOT NULL,
    low numeric(18,6) NOT NULL,
    close numeric(18,6) NOT NULL,
    adj_close numeric(18,6),
    volume bigint NOT NULL,
    vwap numeric(18,6),
    source text NOT NULL,
    ingested_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE theeyebeta.prices_intraday (
    instrument_id bigint NOT NULL,
    ts timestamp with time zone NOT NULL,
    open numeric(16,6),
    high numeric(16,6),
    low numeric(16,6),
    close numeric(16,6),
    volume bigint,
    source text NOT NULL,
    ingested_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE theeyebeta.public_ticker_map (
    instrument_id bigint NOT NULL,
    public_ticker_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE theeyebeta.signals (
    signal_id bigint NOT NULL,
    ticker_id bigint NOT NULL,
    ts timestamp with time zone NOT NULL,
    strategy_name character varying(64) NOT NULL,
    signal character varying(16) NOT NULL,
    confidence numeric(5,4),
    entry_price numeric(18,6),
    target_price numeric(18,6),
    stop_loss numeric(18,6),
    metadata jsonb,
    CONSTRAINT signals_signal_check CHECK (((signal)::text = ANY ((ARRAY['BUY'::character varying, 'SELL'::character varying, 'HOLD'::character varying, 'STRONG_BUY'::character varying, 'STRONG_SELL'::character varying])::text[])))
);

CREATE VIEW theeyebeta.latest_snapshots AS
 WITH latest_cap AS (
         SELECT DISTINCT ON (market_cap_daily.instrument_id) market_cap_daily.instrument_id,
            market_cap_daily.market_cap,
            market_cap_daily.close_price,
            market_cap_daily.as_of_date
           FROM theeyebeta.market_cap_daily
          WHERE (market_cap_daily.instrument_id IS NOT NULL)
          ORDER BY market_cap_daily.instrument_id, market_cap_daily.as_of_date DESC
        ), latest_tech AS (
         SELECT DISTINCT ON (ind_technical_daily.instrument_id) ind_technical_daily.instrument_id,
            ind_technical_daily.sma_10,
            ind_technical_daily.sma_50,
            ind_technical_daily.sma_200,
            ind_technical_daily.rsi_14,
            ind_technical_daily.macd,
            ind_technical_daily.macd_signal,
            ind_technical_daily.macd_hist,
            ind_technical_daily.date
           FROM theeyebeta.ind_technical_daily
          ORDER BY ind_technical_daily.instrument_id, ind_technical_daily.date DESC
        ), ranked_ticks AS (
         SELECT ticks.instrument_id,
            ticks.ts,
            ticks.close,
            ticks.volume,
            row_number() OVER (PARTITION BY ticks.instrument_id ORDER BY ticks.ts DESC) AS rn
           FROM ( SELECT prices_daily.instrument_id,
                    prices_daily.ts,
                    prices_daily.close,
                    prices_daily.volume
                   FROM theeyebeta.prices_daily
                UNION ALL
                 SELECT prices_intraday.instrument_id,
                    prices_intraday.ts,
                    prices_intraday.close,
                    prices_intraday.volume
                   FROM theeyebeta.prices_intraday) ticks
        ), latest_tick AS (
         SELECT ranked_ticks.instrument_id,
            ranked_ticks.ts AS last_price_ts,
            ranked_ticks.close AS last_price,
            ranked_ticks.volume
           FROM ranked_ticks
          WHERE (ranked_ticks.rn = 1)
        ), ranked_daily AS (
         SELECT prices_daily.instrument_id,
            prices_daily.close,
            row_number() OVER (PARTITION BY prices_daily.instrument_id ORDER BY prices_daily.ts DESC) AS rn
           FROM theeyebeta.prices_daily
        ), prev_daily_close AS (
         SELECT ranked_daily.instrument_id,
            ranked_daily.close AS prev_close
           FROM ranked_daily
          WHERE (ranked_daily.rn = 2)
        ), latest_signal AS (
         SELECT DISTINCT ON (m.instrument_id) m.instrument_id,
            s.signal AS latest_signal
           FROM (theeyebeta.signals s
             JOIN theeyebeta.public_ticker_map m ON ((m.public_ticker_id = s.ticker_id)))
          ORDER BY m.instrument_id, s.ts DESC
        ), effective_price AS (
         SELECT COALESCE(lc_1.instrument_id, tick_1.instrument_id) AS instrument_id,
                CASE
                    WHEN (tick_1.last_price_ts IS NULL) THEN lc_1.close_price
                    WHEN (lc_1.as_of_date IS NULL) THEN tick_1.last_price
                    WHEN (tick_1.last_price_ts >= (lc_1.as_of_date)::timestamp with time zone) THEN tick_1.last_price
                    ELSE lc_1.close_price
                END AS last_price,
                CASE
                    WHEN (tick_1.last_price_ts IS NULL) THEN (lc_1.as_of_date)::timestamp with time zone
                    WHEN (lc_1.as_of_date IS NULL) THEN tick_1.last_price_ts
                    WHEN (tick_1.last_price_ts >= (lc_1.as_of_date)::timestamp with time zone) THEN tick_1.last_price_ts
                    ELSE (lc_1.as_of_date)::timestamp with time zone
                END AS last_price_ts
           FROM (latest_cap lc_1
             FULL JOIN latest_tick tick_1 ON ((tick_1.instrument_id = lc_1.instrument_id)))
        )
 SELECT COALESCE(lc.instrument_id, lt.instrument_id, tick.instrument_id) AS instrument_id,
    lc.market_cap,
    ep.last_price,
    ep.last_price_ts,
        CASE
            WHEN ((pdc.prev_close IS NOT NULL) AND (pdc.prev_close <> (0)::numeric)) THEN (((ep.last_price - pdc.prev_close) / pdc.prev_close) * (100)::numeric)
            ELSE NULL::numeric
        END AS price_change_pct,
        CASE
            WHEN (pdc.prev_close IS NOT NULL) THEN (ep.last_price - pdc.prev_close)
            ELSE NULL::numeric
        END AS price_change_abs,
    tick.volume,
    lt.sma_10,
    lt.sma_50,
    lt.sma_200,
    lt.rsi_14,
    lt.macd,
    lt.macd_signal,
    lt.macd_hist,
    sig.latest_signal,
    (LEAST(lc.as_of_date, lt.date))::timestamp with time zone AS updated_at
   FROM (((((latest_cap lc
     FULL JOIN latest_tech lt ON ((lt.instrument_id = lc.instrument_id)))
     FULL JOIN latest_tick tick ON ((tick.instrument_id = COALESCE(lc.instrument_id, lt.instrument_id))))
     LEFT JOIN prev_daily_close pdc ON ((pdc.instrument_id = COALESCE(lc.instrument_id, lt.instrument_id, tick.instrument_id))))
     LEFT JOIN latest_signal sig ON ((sig.instrument_id = COALESCE(lc.instrument_id, lt.instrument_id, tick.instrument_id))))
     LEFT JOIN effective_price ep ON ((ep.instrument_id = COALESCE(lc.instrument_id, lt.instrument_id, tick.instrument_id))));

CREATE TABLE theeyebeta.macro_indicators (
    id bigint NOT NULL,
    series_code text NOT NULL,
    ts timestamp with time zone NOT NULL,
    value numeric(20,6) NOT NULL,
    source text NOT NULL
);

CREATE SEQUENCE theeyebeta.macro_indicators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.macro_indicators_id_seq OWNED BY theeyebeta.macro_indicators.id;

CREATE SEQUENCE theeyebeta.market_cap_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.market_cap_daily_id_seq OWNED BY theeyebeta.market_cap_daily.id;

CREATE TABLE theeyebeta.market_news (
    id bigint NOT NULL,
    provider text NOT NULL,
    url text NOT NULL,
    headline text NOT NULL,
    summary text,
    source text,
    category text,
    related text,
    published_at timestamp with time zone NOT NULL,
    content_hash text NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE theeyebeta.market_news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.market_news_id_seq OWNED BY theeyebeta.market_news.id;

CREATE TABLE theeyebeta.orders (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    client_order_id text NOT NULL,
    broker_order_id text,
    portfolio_id uuid NOT NULL,
    instrument_id bigint NOT NULL,
    decision_id uuid,
    side text NOT NULL,
    order_type text NOT NULL,
    qty numeric(20,6) NOT NULL,
    limit_price numeric(18,6),
    stop_price numeric(18,6),
    time_in_force text DEFAULT 'day'::text NOT NULL,
    status text DEFAULT 'pending_approval'::text NOT NULL,
    approved_by text,
    approved_at timestamp with time zone,
    submitted_at timestamp with time zone,
    filled_qty numeric(20,6) DEFAULT 0 NOT NULL,
    avg_fill_price numeric(18,6),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    submitted_by text,
    CONSTRAINT orders_order_type_check CHECK ((order_type = ANY (ARRAY['market'::text, 'limit'::text, 'stop'::text, 'stop_limit'::text, 'trailing_stop'::text]))),
    CONSTRAINT orders_side_check CHECK ((side = ANY (ARRAY['buy'::text, 'sell'::text]))),
    CONSTRAINT orders_status_check CHECK ((status = ANY (ARRAY['pending_approval'::text, 'approved'::text, 'submitted'::text, 'accepted'::text, 'partially_filled'::text, 'filled'::text, 'cancelled'::text, 'rejected'::text, 'expired'::text])))
);

CREATE TABLE theeyebeta.positions (
    id bigint NOT NULL,
    portfolio_id uuid NOT NULL,
    instrument_id bigint NOT NULL,
    qty numeric(20,6) NOT NULL,
    avg_entry_price numeric(18,6) NOT NULL,
    market_value numeric(20,6),
    unrealized_pnl numeric(20,6),
    realized_pnl numeric(20,6),
    opened_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE theeyebeta.positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.positions_id_seq OWNED BY theeyebeta.positions.id;

CREATE TABLE theeyebeta.sector_daily (
    sector text NOT NULL,
    as_of_date date NOT NULL,
    n_instruments integer DEFAULT 0 NOT NULL,
    avg_return_1d numeric(12,6),
    avg_return_5d numeric(12,6),
    avg_return_30d numeric(12,6),
    median_rsi_14 numeric(8,4),
    pct_above_sma_50 numeric(6,4),
    pct_above_sma_200 numeric(6,4),
    rel_strength_spx_30d numeric(12,6),
    rotation_rank smallint,
    volume_ratio_20d numeric(12,6),
    top_contributors jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE theeyebeta.signals_signal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.signals_signal_id_seq OWNED BY theeyebeta.signals.signal_id;

CREATE TABLE theeyebeta.trading_calendar (
    calendar_date date NOT NULL,
    is_trading_day boolean DEFAULT true NOT NULL,
    market_name text DEFAULT 'US'::text NOT NULL,
    holiday_name text,
    notes text
);

CREATE TABLE theeyebeta.trask_components (
    id integer NOT NULL,
    component_type character varying(32) NOT NULL,
    component_id character varying(64) NOT NULL,
    display_name character varying(128) NOT NULL,
    state character varying(32) DEFAULT 'STOPPED'::character varying NOT NULL,
    last_heartbeat timestamp with time zone,
    last_state_change timestamp with time zone DEFAULT now() NOT NULL,
    error_count integer DEFAULT 0 NOT NULL,
    restart_count integer DEFAULT 0 NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT trask_components_valid_state CHECK (((state)::text = ANY ((ARRAY['STOPPED'::character varying, 'STARTING'::character varying, 'RUNNING'::character varying, 'DEGRADED'::character varying, 'STOPPING'::character varying, 'FAILED'::character varying, 'RETIRED'::character varying])::text[])))
);

CREATE SEQUENCE theeyebeta.trask_components_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE theeyebeta.trask_components_id_seq OWNED BY theeyebeta.trask_components.id;

CREATE TABLE theeyebeta.worker_heartbeats (
    worker_id character varying(64) NOT NULL,
    worker_type character varying(32) NOT NULL,
    status character varying(16) NOT NULL,
    last_heartbeat timestamp with time zone DEFAULT now() NOT NULL,
    started_at timestamp with time zone,
    restart_count integer DEFAULT 0,
    last_error text,
    metadata jsonb,
    CONSTRAINT worker_heartbeats_status_check CHECK (((status)::text = ANY ((ARRAY['running'::character varying, 'stopped'::character varying, 'failed'::character varying, 'restarting'::character varying, 'retired'::character varying])::text[])))
);

ALTER TABLE ONLY theeyebeta.audit_log ATTACH PARTITION theeyebeta.audit_log_2026_10 FOR VALUES FROM ('2026-10-01 00:00:00+00') TO ('2026-11-01 00:00:00+00');

ALTER TABLE ONLY theeyebeta.audit_log ATTACH PARTITION theeyebeta.audit_log_2026_11 FOR VALUES FROM ('2026-11-01 00:00:00+00') TO ('2026-12-01 00:00:00+00');

ALTER TABLE ONLY theeyebeta.audit_log ATTACH PARTITION theeyebeta.audit_log_2026_12 FOR VALUES FROM ('2026-12-01 00:00:00+00') TO ('2027-01-01 00:00:00+00');

ALTER TABLE ONLY theeyebeta.audit_log ATTACH PARTITION theeyebeta.audit_log_2027_01 FOR VALUES FROM ('2027-01-01 00:00:00+00') TO ('2027-02-01 00:00:00+00');

ALTER TABLE ONLY theeyebeta.audit_log ATTACH PARTITION theeyebeta.audit_log_2027_02 FOR VALUES FROM ('2027-02-01 00:00:00+00') TO ('2027-03-01 00:00:00+00');

ALTER TABLE ONLY theeyebeta.audit_log ATTACH PARTITION theeyebeta.audit_log_2027_03 FOR VALUES FROM ('2027-03-01 00:00:00+00') TO ('2027-04-01 00:00:00+00');

ALTER TABLE ONLY theeyebeta.audit_log ATTACH PARTITION theeyebeta.audit_log_2027_04 FOR VALUES FROM ('2027-04-01 00:00:00+00') TO ('2027-05-01 00:00:00+00');

ALTER TABLE ONLY theeyebeta.audit_cap_events ALTER COLUMN id SET DEFAULT nextval('theeyebeta.audit_cap_events_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.audit_log ALTER COLUMN id SET DEFAULT nextval('theeyebeta.audit_log_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.corporate_actions ALTER COLUMN id SET DEFAULT nextval('theeyebeta.corporate_actions_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.exchanges ALTER COLUMN id SET DEFAULT nextval('theeyebeta.exchanges_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.fixed_income_signals ALTER COLUMN id SET DEFAULT nextval('theeyebeta.fixed_income_signals_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.fundamentals ALTER COLUMN id SET DEFAULT nextval('theeyebeta.fundamentals_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.instruments ALTER COLUMN id SET DEFAULT nextval('theeyebeta.instruments_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.macro_indicators ALTER COLUMN id SET DEFAULT nextval('theeyebeta.macro_indicators_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.market_cap_daily ALTER COLUMN id SET DEFAULT nextval('theeyebeta.market_cap_daily_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.market_news ALTER COLUMN id SET DEFAULT nextval('theeyebeta.market_news_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.positions ALTER COLUMN id SET DEFAULT nextval('theeyebeta.positions_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.signals ALTER COLUMN signal_id SET DEFAULT nextval('theeyebeta.signals_signal_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.trask_components ALTER COLUMN id SET DEFAULT nextval('theeyebeta.trask_components_id_seq'::regclass);

ALTER TABLE ONLY theeyebeta.audit_cap_events
    ADD CONSTRAINT audit_cap_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id, ts);

ALTER TABLE ONLY theeyebeta.audit_log_2026_10
    ADD CONSTRAINT audit_log_2026_10_pkey PRIMARY KEY (id, ts);

ALTER TABLE ONLY theeyebeta.audit_log_2026_11
    ADD CONSTRAINT audit_log_2026_11_pkey PRIMARY KEY (id, ts);

ALTER TABLE ONLY theeyebeta.audit_log_2026_12
    ADD CONSTRAINT audit_log_2026_12_pkey PRIMARY KEY (id, ts);

ALTER TABLE ONLY theeyebeta.audit_log_2027_01
    ADD CONSTRAINT audit_log_2027_01_pkey PRIMARY KEY (id, ts);

ALTER TABLE ONLY theeyebeta.audit_log_2027_02
    ADD CONSTRAINT audit_log_2027_02_pkey PRIMARY KEY (id, ts);

ALTER TABLE ONLY theeyebeta.audit_log_2027_03
    ADD CONSTRAINT audit_log_2027_03_pkey PRIMARY KEY (id, ts);

ALTER TABLE ONLY theeyebeta.audit_log_2027_04
    ADD CONSTRAINT audit_log_2027_04_pkey PRIMARY KEY (id, ts);

ALTER TABLE theeyebeta.orders
    ADD CONSTRAINT ck_orders_qty_positive CHECK ((qty > (0)::numeric)) NOT VALID;

ALTER TABLE ONLY theeyebeta.corporate_actions
    ADD CONSTRAINT corporate_actions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.dataapi_applications
    ADD CONSTRAINT dataapi_applications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.dataapi_credential_revocations
    ADD CONSTRAINT dataapi_credential_revocations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.dataapi_entitlements
    ADD CONSTRAINT dataapi_entitlements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.dataapi_locks
    ADD CONSTRAINT dataapi_locks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.dataapi_memberships
    ADD CONSTRAINT dataapi_memberships_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.dataapi_policy_versions
    ADD CONSTRAINT dataapi_policy_versions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.dataapi_tenants
    ADD CONSTRAINT dataapi_tenants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.exchanges
    ADD CONSTRAINT exchanges_code_key UNIQUE (code);

ALTER TABLE ONLY theeyebeta.exchanges
    ADD CONSTRAINT exchanges_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.fixed_income_curve_metrics
    ADD CONSTRAINT fixed_income_curve_metrics_pkey PRIMARY KEY (date, country);

ALTER TABLE ONLY theeyebeta.fixed_income_signals
    ADD CONSTRAINT fixed_income_signals_date_country_signal_name_key UNIQUE (date, country, signal_name);

ALTER TABLE ONLY theeyebeta.fixed_income_signals
    ADD CONSTRAINT fixed_income_signals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.fundamentals
    ADD CONSTRAINT fundamentals_instrument_id_period_end_period_type_source_key UNIQUE (instrument_id, period_end, period_type, source);

ALTER TABLE ONLY theeyebeta.fundamentals
    ADD CONSTRAINT fundamentals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.ind_technical_daily
    ADD CONSTRAINT ind_technical_daily_pkey PRIMARY KEY (instrument_id, date);

ALTER TABLE ONLY theeyebeta.instruments
    ADD CONSTRAINT instruments_figi_key UNIQUE (figi);

ALTER TABLE ONLY theeyebeta.instruments
    ADD CONSTRAINT instruments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.instruments
    ADD CONSTRAINT instruments_symbol_exchange_id_key UNIQUE (symbol, exchange_id);

ALTER TABLE ONLY theeyebeta.macro_indicators
    ADD CONSTRAINT macro_indicators_series_code_ts_key UNIQUE (series_code, ts);

ALTER TABLE ONLY theeyebeta.market_cap_daily
    ADD CONSTRAINT market_cap_daily_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.market_cap_daily
    ADD CONSTRAINT market_cap_daily_symbol_as_of_date_key UNIQUE (symbol, as_of_date);

ALTER TABLE ONLY theeyebeta.market_news
    ADD CONSTRAINT market_news_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.market_news
    ADD CONSTRAINT market_news_provider_url_key UNIQUE (provider, url);

ALTER TABLE ONLY theeyebeta.orders
    ADD CONSTRAINT orders_client_order_id_key UNIQUE (client_order_id);

ALTER TABLE ONLY theeyebeta.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.dataapi_quota_windows
    ADD CONSTRAINT pk_dataapi_quota_windows PRIMARY KEY (tenant_id, subject, window_started_at);

ALTER TABLE ONLY theeyebeta.positions
    ADD CONSTRAINT positions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.positions
    ADD CONSTRAINT positions_portfolio_id_instrument_id_key UNIQUE (portfolio_id, instrument_id);

ALTER TABLE ONLY theeyebeta.public_ticker_map
    ADD CONSTRAINT public_ticker_map_pkey PRIMARY KEY (instrument_id);

ALTER TABLE ONLY theeyebeta.public_ticker_map
    ADD CONSTRAINT public_ticker_map_public_ticker_id_key UNIQUE (public_ticker_id);

ALTER TABLE ONLY theeyebeta.sector_daily
    ADD CONSTRAINT sector_daily_pkey PRIMARY KEY (sector, as_of_date);

ALTER TABLE ONLY theeyebeta.signals
    ADD CONSTRAINT signals_ticker_id_ts_strategy_name_key UNIQUE (ticker_id, ts, strategy_name);

ALTER TABLE ONLY theeyebeta.trading_calendar
    ADD CONSTRAINT trading_calendar_pkey PRIMARY KEY (calendar_date);

ALTER TABLE ONLY theeyebeta.trask_components
    ADD CONSTRAINT trask_components_component_id_key UNIQUE (component_id);

ALTER TABLE ONLY theeyebeta.trask_components
    ADD CONSTRAINT trask_components_pkey PRIMARY KEY (id);

ALTER TABLE ONLY theeyebeta.dataapi_applications
    ADD CONSTRAINT uq_dataapi_applications_client_id UNIQUE (client_id);

ALTER TABLE ONLY theeyebeta.dataapi_credential_revocations
    ADD CONSTRAINT uq_dataapi_credential_revocations_token_id UNIQUE (token_id);

ALTER TABLE ONLY theeyebeta.dataapi_entitlements
    ADD CONSTRAINT uq_dataapi_entitlements_scope UNIQUE (tenant_id, policy_version_id, code);

ALTER TABLE ONLY theeyebeta.dataapi_locks
    ADD CONSTRAINT uq_dataapi_locks_idempotency_key UNIQUE (idempotency_key);

ALTER TABLE ONLY theeyebeta.dataapi_memberships
    ADD CONSTRAINT uq_dataapi_memberships_tenant_subject UNIQUE (tenant_id, external_subject);

ALTER TABLE ONLY theeyebeta.dataapi_policy_versions
    ADD CONSTRAINT uq_dataapi_policy_versions_version UNIQUE (version);

ALTER TABLE ONLY theeyebeta.dataapi_tenants
    ADD CONSTRAINT uq_dataapi_tenants_slug UNIQUE (slug);

ALTER TABLE ONLY theeyebeta.worker_heartbeats
    ADD CONSTRAINT worker_heartbeats_pkey PRIMARY KEY (worker_id);

CREATE INDEX idx_audit_actor_ts ON ONLY theeyebeta.audit_log USING btree (actor, ts DESC);

CREATE INDEX audit_log_2026_10_actor_ts_idx ON theeyebeta.audit_log_2026_10 USING btree (actor, ts DESC);

CREATE INDEX idx_audit_entity ON ONLY theeyebeta.audit_log USING btree (entity_type, entity_id);

CREATE INDEX audit_log_2026_10_entity_type_entity_id_idx ON theeyebeta.audit_log_2026_10 USING btree (entity_type, entity_id);

CREATE INDEX audit_log_2026_11_actor_ts_idx ON theeyebeta.audit_log_2026_11 USING btree (actor, ts DESC);

CREATE INDEX audit_log_2026_11_entity_type_entity_id_idx ON theeyebeta.audit_log_2026_11 USING btree (entity_type, entity_id);

CREATE INDEX audit_log_2026_12_actor_ts_idx ON theeyebeta.audit_log_2026_12 USING btree (actor, ts DESC);

CREATE INDEX audit_log_2026_12_entity_type_entity_id_idx ON theeyebeta.audit_log_2026_12 USING btree (entity_type, entity_id);

CREATE INDEX audit_log_2027_01_actor_ts_idx ON theeyebeta.audit_log_2027_01 USING btree (actor, ts DESC);

CREATE INDEX audit_log_2027_01_entity_type_entity_id_idx ON theeyebeta.audit_log_2027_01 USING btree (entity_type, entity_id);

CREATE INDEX audit_log_2027_02_actor_ts_idx ON theeyebeta.audit_log_2027_02 USING btree (actor, ts DESC);

CREATE INDEX audit_log_2027_02_entity_type_entity_id_idx ON theeyebeta.audit_log_2027_02 USING btree (entity_type, entity_id);

CREATE INDEX audit_log_2027_03_actor_ts_idx ON theeyebeta.audit_log_2027_03 USING btree (actor, ts DESC);

CREATE INDEX audit_log_2027_03_entity_type_entity_id_idx ON theeyebeta.audit_log_2027_03 USING btree (entity_type, entity_id);

CREATE INDEX audit_log_2027_04_actor_ts_idx ON theeyebeta.audit_log_2027_04 USING btree (actor, ts DESC);

CREATE INDEX audit_log_2027_04_entity_type_entity_id_idx ON theeyebeta.audit_log_2027_04 USING btree (entity_type, entity_id);

CREATE UNIQUE INDEX fundamentals_company_instrument_uniq ON theeyebeta.fundamentals_company USING btree (instrument_id);

CREATE UNIQUE INDEX fundamentals_company_source_ticker_uniq ON theeyebeta.fundamentals_company USING btree (ticker_id);

CREATE INDEX idx_audit_cap_events_date_type ON theeyebeta.audit_cap_events USING btree (trade_date DESC, event_type);

CREATE INDEX idx_audit_cap_events_false_positive ON theeyebeta.audit_cap_events USING btree (is_false_positive) WHERE is_false_positive;

CREATE INDEX idx_corp_actions_inst_date ON theeyebeta.corporate_actions USING btree (instrument_id, ex_date);

CREATE INDEX idx_dataapi_locks_active_scope ON theeyebeta.dataapi_locks USING btree (scope_type, scope_id) WHERE (active = true);

CREATE INDEX idx_dataapi_memberships_subject ON theeyebeta.dataapi_memberships USING btree (external_subject);

CREATE INDEX idx_dataapi_revocations_expires ON theeyebeta.dataapi_credential_revocations USING btree (expires_at);

CREATE INDEX idx_fixed_income_curve_metrics_country_date ON theeyebeta.fixed_income_curve_metrics USING btree (country, date DESC);

CREATE INDEX idx_fixed_income_curve_metrics_label ON theeyebeta.fixed_income_curve_metrics USING btree (bond_environment_label);

CREATE INDEX idx_fixed_income_signals_country_date ON theeyebeta.fixed_income_signals USING btree (country, date DESC);

CREATE INDEX idx_fixed_income_signals_name_date ON theeyebeta.fixed_income_signals USING btree (signal_name, date DESC);

CREATE INDEX idx_fundamentals_inst ON theeyebeta.fundamentals USING btree (instrument_id, period_end DESC);

CREATE INDEX idx_ind_technical_daily_date ON theeyebeta.ind_technical_daily USING btree (date DESC);

CREATE INDEX idx_instruments_active ON theeyebeta.instruments USING btree (active) WHERE active;

CREATE INDEX idx_instruments_sector ON theeyebeta.instruments USING btree (sector);

CREATE INDEX idx_market_cap_daily_date_cap ON theeyebeta.market_cap_daily USING btree (as_of_date DESC, market_cap DESC);

CREATE INDEX idx_market_cap_daily_instrument_date ON theeyebeta.market_cap_daily USING btree (instrument_id, as_of_date DESC);

CREATE INDEX idx_orders_inst_created ON theeyebeta.orders USING btree (instrument_id, created_at DESC);

CREATE INDEX idx_orders_portfolio_status ON theeyebeta.orders USING btree (portfolio_id, status);

CREATE UNIQUE INDEX idx_prices_daily_uniq ON theeyebeta.prices_daily USING btree (instrument_id, ts);

CREATE UNIQUE INDEX idx_prices_intraday_inst_ts ON theeyebeta.prices_intraday USING btree (instrument_id, ts);

CREATE INDEX idx_public_ticker_map_public_id ON theeyebeta.public_ticker_map USING btree (public_ticker_id);

CREATE INDEX idx_sector_daily_date ON theeyebeta.sector_daily USING btree (as_of_date DESC);

CREATE INDEX idx_trading_calendar_trading_day ON theeyebeta.trading_calendar USING btree (is_trading_day, calendar_date);

CREATE INDEX idx_trask_components_state ON theeyebeta.trask_components USING btree (state);

CREATE INDEX idx_trask_components_type ON theeyebeta.trask_components USING btree (component_type);

CREATE INDEX idx_worker_heartbeats_type ON theeyebeta.worker_heartbeats USING btree (worker_type);

CREATE INDEX macro_indicators_ts_idx ON theeyebeta.macro_indicators USING btree (ts DESC);

CREATE INDEX prices_daily_ts_idx ON theeyebeta.prices_daily USING btree (ts DESC);

CREATE INDEX prices_intraday_ts_idx1 ON theeyebeta.prices_intraday USING btree (ts DESC);

CREATE INDEX signals_ticker_id_ts_idx ON theeyebeta.signals USING btree (ticker_id, ts DESC);

CREATE INDEX signals_ts_idx1 ON theeyebeta.signals USING btree (ts DESC);

CREATE UNIQUE INDEX uq_dataapi_policy_versions_one_active ON theeyebeta.dataapi_policy_versions USING btree (status) WHERE (status = 'ACTIVE'::text);

ALTER INDEX theeyebeta.idx_audit_actor_ts ATTACH PARTITION theeyebeta.audit_log_2026_10_actor_ts_idx;

ALTER INDEX theeyebeta.idx_audit_entity ATTACH PARTITION theeyebeta.audit_log_2026_10_entity_type_entity_id_idx;

ALTER INDEX theeyebeta.audit_log_pkey ATTACH PARTITION theeyebeta.audit_log_2026_10_pkey;

ALTER INDEX theeyebeta.idx_audit_actor_ts ATTACH PARTITION theeyebeta.audit_log_2026_11_actor_ts_idx;

ALTER INDEX theeyebeta.idx_audit_entity ATTACH PARTITION theeyebeta.audit_log_2026_11_entity_type_entity_id_idx;

ALTER INDEX theeyebeta.audit_log_pkey ATTACH PARTITION theeyebeta.audit_log_2026_11_pkey;

ALTER INDEX theeyebeta.idx_audit_actor_ts ATTACH PARTITION theeyebeta.audit_log_2026_12_actor_ts_idx;

ALTER INDEX theeyebeta.idx_audit_entity ATTACH PARTITION theeyebeta.audit_log_2026_12_entity_type_entity_id_idx;

ALTER INDEX theeyebeta.audit_log_pkey ATTACH PARTITION theeyebeta.audit_log_2026_12_pkey;

ALTER INDEX theeyebeta.idx_audit_actor_ts ATTACH PARTITION theeyebeta.audit_log_2027_01_actor_ts_idx;

ALTER INDEX theeyebeta.idx_audit_entity ATTACH PARTITION theeyebeta.audit_log_2027_01_entity_type_entity_id_idx;

ALTER INDEX theeyebeta.audit_log_pkey ATTACH PARTITION theeyebeta.audit_log_2027_01_pkey;

ALTER INDEX theeyebeta.idx_audit_actor_ts ATTACH PARTITION theeyebeta.audit_log_2027_02_actor_ts_idx;

ALTER INDEX theeyebeta.idx_audit_entity ATTACH PARTITION theeyebeta.audit_log_2027_02_entity_type_entity_id_idx;

ALTER INDEX theeyebeta.audit_log_pkey ATTACH PARTITION theeyebeta.audit_log_2027_02_pkey;

ALTER INDEX theeyebeta.idx_audit_actor_ts ATTACH PARTITION theeyebeta.audit_log_2027_03_actor_ts_idx;

ALTER INDEX theeyebeta.idx_audit_entity ATTACH PARTITION theeyebeta.audit_log_2027_03_entity_type_entity_id_idx;

ALTER INDEX theeyebeta.audit_log_pkey ATTACH PARTITION theeyebeta.audit_log_2027_03_pkey;

ALTER INDEX theeyebeta.idx_audit_actor_ts ATTACH PARTITION theeyebeta.audit_log_2027_04_actor_ts_idx;

ALTER INDEX theeyebeta.idx_audit_entity ATTACH PARTITION theeyebeta.audit_log_2027_04_entity_type_entity_id_idx;

ALTER INDEX theeyebeta.audit_log_pkey ATTACH PARTITION theeyebeta.audit_log_2027_04_pkey;
