#!/usr/bin/env python3
"""Regenerate contracts/prod/admin_route_families.json from TheEyeBetaProd.

Imports TheEyeBetaProd's admin-service FastAPI app (services/admin_service) and
records, for every route family in this repo's ADMIN_ROUTE_MANIFEST, the HTTP
methods admin-service actually implements under it, plus every admin-service
route no family covers. tests/test_admin_gateway_contract.py holds the
manifest to this file, so the gateway can neither expose a method Prod does
not implement nor silently miss a route Prod adds.

Only family-level data is stored (this repository is public); individual
admin-service paths stay in Prod.

Run with a Python environment that can import admin-service (its pyproject
dependencies plus libs/theeyebeta_schemas and services/audit_service):

    PROD_REPO=../TheEyeBetaProd PROD_SHA=<sha> python scripts/prod_contract_admin_routes.py
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT = REPO_ROOT / "contracts" / "prod" / "admin_route_families.json"
IGNORED_METHODS = {"HEAD", "OPTIONS"}


def _prod_routes(prod_repo: Path) -> list[tuple[str, str]]:
    service_dir = prod_repo / "services" / "admin_service"
    os.environ.setdefault("ADMIN_JWT_SECRET", "contract-generation-only-" + "x" * 40)
    sys.path.insert(0, str(service_dir))
    os.chdir(service_dir)
    import main  # type: ignore[import-not-found]  # Prod admin-service entry point

    found: set[tuple[str, str]] = set()
    for path, operations in main.app.openapi()["paths"].items():
        for method in operations:
            found.add((method.upper(), path))

    def walk(routes: list[object]) -> None:
        for route in routes:
            methods = getattr(route, "methods", None)
            path = getattr(route, "path", None)
            if methods and path:
                for method in methods - IGNORED_METHODS:
                    found.add((method, path))
            children = getattr(route, "routes", None)
            if children:
                walk(children)

    walk(main.app.routes)
    return sorted(found)


def main() -> int:
    prod_repo = Path(os.environ["PROD_REPO"]).resolve()
    expected_sha = os.environ["PROD_SHA"]
    actual_sha = subprocess.run(
        ["git", "-C", str(prod_repo), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    ).stdout.strip()
    if actual_sha != expected_sha:
        print(f"Prod checkout is at {actual_sha}, expected {expected_sha}", file=sys.stderr)
        return 1

    sys.path.insert(0, str(REPO_ROOT))
    os.environ.setdefault("DATABASE_URL", "postgresql+psycopg://contract:contract@127.0.0.1:1/contract")
    os.environ.setdefault("JWT_SECRET", "contract-generation-only-jwt-secret-32b")
    from app.api.routes.admin_gateway import ADMIN_ROUTE_MANIFEST

    prefixes = [rule.prefix.strip("/") for rule in ADMIN_ROUTE_MANIFEST]
    families: dict[str, set[str]] = {prefix: set() for prefix in prefixes}
    uncovered: set[tuple[str, str]] = set()
    for method, path in _prod_routes(prod_repo):
        if not path.startswith("/admin/"):
            continue
        relative = path[len("/admin/") :]
        # Same first-match rule as admin_gateway.is_allowed_admin_route.
        family = next(
            (p for p in prefixes if relative == p or relative.startswith(f"{p}/") or (p.endswith("/") and relative.startswith(p))),
            None,
        )
        if family is None:
            uncovered.add((method, re.sub(r"\{[^}]+\}", "{param}", relative)))
        else:
            families[family].add(method)

    payload = {
        "_comment": "GENERATED by scripts/prod_contract_admin_routes.py. Do not edit by hand.",
        "prod_sha": expected_sha,
        "families": {prefix: sorted(methods) for prefix, methods in families.items()},
        "uncovered": [list(item) for item in sorted(uncovered)],
    }
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
