#!/usr/bin/env bash
# Regenerate contracts/prod/theeyebeta_schema.sql from a TheEyeBetaProd checkout.
#
# The snapshot holds the structure (columns, types, constraints other than
# foreign keys, indexes, views) of ONLY the theeyebeta objects this API reads,
# produced by running Prod's real Alembic migrations. tests/contract applies it
# to an empty PostgreSQL and drives the HTTP API against it.
#
# Requires: a TimescaleDB + pgvector PostgreSQL 16 you can create databases on
# (e.g. docker run -p 55433:5432 -e POSTGRES_PASSWORD=postgres timescale/timescaledb-ha:pg16),
# Prod's Python deps for Alembic (alembic, sqlalchemy, psycopg), pg_dump 16.
#
# Usage:
#   PROD_REPO=../TheEyeBetaProd PROD_SHA=<sha> \
#   ADMIN_URL=postgresql://postgres:postgres@127.0.0.1:55433/postgres \
#   bash scripts/prod_contract_snapshot.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
: "${PROD_REPO:?Set PROD_REPO to a TheEyeBetaProd checkout}"
: "${PROD_SHA:?Set PROD_SHA to the Prod commit the snapshot must match}"
: "${ADMIN_URL:?Set ADMIN_URL to a superuser libpq URL on a scratch TimescaleDB server}"
OUT="$REPO_DIR/contracts/prod/theeyebeta_schema.sql"
OBJECTS="$REPO_DIR/contracts/prod/objects.txt"
DB="dataapi_contract_$$"

actual_sha="$(git -C "$PROD_REPO" rev-parse HEAD)"
if [[ "$actual_sha" != "$PROD_SHA" ]]; then
  echo "Prod checkout is at $actual_sha, expected $PROD_SHA" >&2
  exit 1
fi

target_url="${ADMIN_URL%/*}/$DB"
cleanup() { psql "$ADMIN_URL" -qc "DROP DATABASE IF EXISTS \"$DB\" WITH (FORCE)" >/dev/null 2>&1 || true; }
trap cleanup EXIT

psql "$ADMIN_URL" -v ON_ERROR_STOP=1 -qc "CREATE DATABASE \"$DB\""
# Prod's own test bootstrap (extensions, schema, roles), then its migrations.
sed "s/DATABASE theeyebeta/DATABASE \"$DB\"/" "$PROD_REPO/services/data_ingestion/tests/sql/bootstrap.sql" \
  | psql "$target_url" -v ON_ERROR_STOP=1 -q
(cd "$PROD_REPO/db" && DATABASE_URL="${target_url/postgresql:/postgresql+psycopg:}" \
  LITELLM_DB_PASSWORD="contract_snapshot_only" alembic -c alembic.ini upgrade head >/dev/null 2>&1) \
  || { echo "Prod migrations failed; rerun without redirection to see why" >&2; exit 1; }
head_rev="$(psql "$target_url" -tAc 'SELECT version_num FROM theeyebeta.alembic_version')"

# Objects to snapshot: every theeyebeta object listed in objects.txt plus the
# view base tables and partitions they need. Foreign keys are dropped below,
# so FK targets (Prod's agent/account tables) stay out of this public repo.
mapfile -t wanted < <(grep -vE '^\s*(#|$)' "$OBJECTS")
args=()
for name in "${wanted[@]}"; do args+=(--table-and-children "theeyebeta.${name}"); done

{
  echo "-- GENERATED by scripts/prod_contract_snapshot.sh. Do not edit by hand."
  echo "-- Source: TheEyeBetaProd @ ${PROD_SHA} (alembic head ${head_rev})"
  echo "-- Objects: contracts/prod/objects.txt (theeyebeta objects TheEyeBetaDataAPI reads)"
  echo "CREATE SCHEMA IF NOT EXISTS theeyebeta;"
  pg_dump "$target_url" --schema-only --no-owner --no-privileges --no-comments \
      --no-publications --no-subscriptions --no-security-labels "${args[@]}" \
    | python3 "$REPO_DIR/scripts/_strip_prod_snapshot.py"
} > "$OUT"
# Grants Prod's migrations give the DataAPI policy role (contract C1). Exported
# as data so tests/contract can recreate exactly what Prod grants, no more.
{
  echo "-- GENERATED by scripts/prod_contract_snapshot.sh from TheEyeBetaProd @ ${PROD_SHA}."
  echo "-- Role and grants that Prod migrations create for the DataAPI policy reader."
  echo "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'api_readonly') THEN CREATE ROLE api_readonly NOLOGIN; END IF; END \$\$;"
  psql "$target_url" -tA -c "
    SELECT 'GRANT USAGE ON SCHEMA theeyebeta TO api_readonly;'
    WHERE has_schema_privilege('api_readonly', 'theeyebeta', 'USAGE')
    UNION ALL
    SELECT format('GRANT %s ON TABLE theeyebeta.%I TO api_readonly;', string_agg(privilege_type, ', ' ORDER BY privilege_type), table_name)
    FROM information_schema.role_table_grants
    WHERE grantee = 'api_readonly' AND table_schema = 'theeyebeta'
    GROUP BY table_name
    ORDER BY 1"
} > "$REPO_DIR/contracts/prod/api_readonly_grants.sql"
echo "$PROD_SHA" > "$REPO_DIR/contracts/prod/PROD_SHA"
echo "$head_rev" > "$REPO_DIR/contracts/prod/ALEMBIC_HEAD"
echo "Wrote $OUT (Prod ${PROD_SHA:0:12}, head ${head_rev})"
